services:
  database:
    env_file:
      - .env
    image: postgres:17-alpine
    restart: always
    container_name: database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/

  backend-service:
    env_file:
      - .env
    build:
      context: ./backend-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:${POSTGRES_DOCKER_PORT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASS}

    depends_on:
      - database
      - rabbitmq

  agent-service:
    env_file:
      - .env
    build:
      context: ./agent-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${AGENT_SERVICE_PORT}:3721"

  sandbox-service:
    env_file:
      - .env
    build:
      context: ./sandbox-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${SANDBOX_SERVICE_PORT}:2137"

  client:
    env_file:
      - .env
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend-service

volumes:
  postgres_data:
  rabbitmq-lib:
    driver: local